services:
  - type: web
    name: roma-md
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    disk:
      name: roma-auth
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: AUTH_DIR
        value: /var/data/auth_info_baileys
      - key: PORT
        value: "10000"
      - key: OWNER_NUMBER
        sync: false
      - key: WEB_TOKEN
        sync: false
      - key: PREFIX
        value: "."
      - key: MODE
        value: "public"
      - key: BOT_NAME
        value: "ROMA MD"
      - key: LANGUAGE
        value: "English"