services:
  - type: web
    name: roma-md
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SESSION_ID
        sync: false
      - key: SESSION_ENCRYPTION_KEY
        sync: false
      - key: PORT
        value: "10000"
      - key: OWNER_NUMBER
        sync: false
      - key: PREFIX
        value: "."
      - key: MODE
        value: "public"
      - key: BOT_NAME
        value: "ROMA MD"
      - key: LANGUAGE
        value: "English"
